// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class Fing {
	
	protected System.Web.UI.UserControl head;
	
	protected System.Web.UI.UserControl Header;
	
	protected System.Web.UI.WebControls.ContentPlaceHolder Main;
	
	protected System.Web.UI.UserControl TopArea;
	
	protected System.Web.UI.UserControl LeftArea;
	
	protected System.Web.UI.UserControl RightArea;
	
	protected bolsaemp.Footer Footer;
}
