// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace internreg {
	
	
	public partial class javeriana {
		
		protected internreg.Search Search;
		
		protected internreg.MenuBar MenuBar;
		
		protected internreg.Banner Banner;
		
		protected internreg.SideMenu SideMenu;
		
		protected System.Web.UI.HtmlControls.HtmlForm content;
		
		protected System.Web.UI.WebControls.ContentPlaceHolder Main;
		
		protected internreg.Footer Footer;
	}
}
