// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace internreg {
	
	
	public partial class LoginEmp {
		
		protected System.Web.UI.WebControls.MultiView MultiViewEst;
		
		protected System.Web.UI.WebControls.View EmpRegister;
		
		protected System.Web.UI.WebControls.View EmpLogin;
		
		protected System.Web.UI.WebControls.View EmpHelp;
		
		protected System.Web.UI.WebControls.View EmpHello;
	}
}
