// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace internreg {
	
	
	public partial class LoginEst {
		
		protected System.Web.UI.WebControls.MultiView MultiViewEst;
		
		protected System.Web.UI.WebControls.View EstRegister;
		
		protected System.Web.UI.WebControls.TextBox est_email;
		
		protected System.Web.UI.WebControls.Button est_register;
		
		protected System.Web.UI.WebControls.Button EstToReg;
		
		protected System.Web.UI.WebControls.Button est_register_help;
		
		protected System.Web.UI.WebControls.View EstLogin;
		
		protected System.Web.UI.WebControls.Button EstToLog;
		
		protected System.Web.UI.WebControls.TextBox est_usuario;
		
		protected System.Web.UI.WebControls.TextBox est_passwd;
		
		protected System.Web.UI.WebControls.Button est_login;
		
		protected System.Web.UI.WebControls.Button est_login_help;
		
		protected System.Web.UI.WebControls.View EstHelp;
		
		protected System.Web.UI.WebControls.TextBox est_cedula;
		
		protected System.Web.UI.WebControls.Button est_help;
		
		protected System.Web.UI.WebControls.Button esthelp_register;
		
		protected System.Web.UI.WebControls.Button esthelp_login;
		
		protected System.Web.UI.WebControls.View EstHello;
	}
}
