// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace egresados {
	
	
	public partial class Registro {
		
		protected System.Web.UI.WebControls.TextBox documento;
		
		protected System.Web.UI.WebControls.Button begin;
		
		protected System.Web.UI.WebControls.TextBox password;
	}
}
