// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace bolsaemp {
	
	
	public partial class TopArea {
		
		protected bolsaemp.Search Search;
		
		protected bolsaemp.TopMenu TopMenu;
		
		protected bolsaemp.MenuBar MenuBar;
		
		protected bolsaemp.Banner Banner;
	}
}
